L1 = 0.3;
L2 = 0.3;
L3 = 0.3;

robot = SerialLink([Revolute('offset', pi, 'a', 0, 'alpha', pi/2), ...
                    Revolute('offset', -pi/2, 'a', -L1, 'alpha', 0), ...
                    Revolute('offset', 0, 'a', -L2, 'alpha', 0), ...
                    Revolute('offset', 0, 'a', -L3, 'alpha', 0)], ...
                    'name', 'SeanRRR');